Create a button project on samd21 with mbed sdk
Luos-io/luos_engine pull request #245
Opened 2022-06-07 12:50 UTC by Salem-Luos

# PR Checklist 

### _1- PR Comments_
    *If needed, to be filled by developer*  

<br><hr/>
*WARNING : Do not edit the checklist below.*  
<hr/><br>

### _2- Developer section_

- [ ] [Documentation] is up to date with new feature
- [ ] [Tests] are *passed OK* (Non regression, new features & bug fixes)
- [ ] [Code Quality] Remind to check if :
    * Each function has a header (description, inputs, outputs) 
    * Code is commented (particularly in hard to understand areas)
    * There are no new warnings that can be corrected
    * Commits policy is respected (constitancy commits, clear commits comments)
<hr/><br>

### _3- QA section_

- [ ] [Review] tests for new features have been *reviewed*
- [ ] [Changelog] is up-to-date with expected tags  
    🆕 Feature: [Feature] Description...  
    🆕 Added: [Feature] Description...  
    🆕 Changed: [Feature] Description...  
    🛠️ Fix: [Feature] Description...

2022-06-08 09:37 UTC, nicolas-rabault requested changes
This button doesn't read any pin!

2022-06-08 09:37 UTC, nicolas-rabault commented on examples/projects/SAMD21XPLAINED/button/lib/README
> +
You should remove this file.

2022-06-08 09:37 UTC, nicolas-rabault commented on examples/projects/SAMD21XPLAINED/button/lib/button/button.c
> +        pub_msg.data[0]            = true; // BTN VALUE
You should get a real BTN value.

2022-06-20 10:54 UTC, JeromeGalan approved these changes

2022-06-20 11:04 UTC, nicolas-rabault approved these changes
ok

2022-06-20 11:10 UTC, merged