Fix/timestamp localhost
Luos-io/luos_engine pull request #262
Opened 2022-06-28 16:13 UTC by BiliouriV

# PR Checklist 

### _1- PR Comments_
    *If needed, to be filled by developer*  

<br><hr/>
*WARNING : Do not edit the checklist below.*  
<hr/><br>

### _2- Developer section_

- [x] [Documentation] is up to date with new feature
- [x] [Tests] are *passed OK* (Non regression, new features & bug fixes)
- [x] [Code Quality] Remind to check if :
    * Each function has a header (description, inputs, outputs) 
    * Code is commented (particularly in hard to understand areas)
    * There are no new warnings that can be corrected
    * Commits policy is respected (constitancy commits, clear commits comments)
<hr/><br>

### _3- QA section_

- [x] [Review] tests for new features have been *reviewed*
- [x] [Changelog] is up-to-date with expected tags  
    🆕 Feature: [Feature] Description...  
    🆕 Added: [Feature] Description...  
    🆕 Changed: [Feature] Description...  
    🛠️ Fix: [Feature] Description...

2022-06-30 12:36 UTC, nicolas-rabault requested changes
I think this bug still exist if we enable the VERBOSE_LOCALHOST mode...

2022-06-30 12:36 UTC, nicolas-rabault commented on network/robus/src/robus.c
> +#ifndef VERBOSE_LOCALHOST
I think this means that if we are in verbose localhost, timestamps will not work on localhost anymore.

2022-07-04 09:58 UTC, nicolas-rabault approved these changes
Great!

2022-07-04 10:03 UTC, JeromeGalan approved these changes

2022-07-04 10:08 UTC, Salem-Luos approved these changes

2022-07-04 10:56 UTC, merged