Implementing contribution for community
Luos-io/luos_engine pull request #305
Opened 2022-08-02 14:36 UTC by Simonbdy

# PR Checklist 

### _1- PR Comments_
    We are implementing the contribution for the Luos community. This PR is about updating the file *contributing.md*.  

<br><hr/>
*WARNING : Do not edit the checklist below.*  
<hr/><br>

### _2- Developer section_

- [ ] [Documentation] is up to date with new feature
- [ ] [Tests] are *passed OK* (Non regression, new features & bug fixes)
- [ ] [Code Quality] Remind to check if :
    * Each function has a header (description, inputs, outputs) 
    * Code is commented (particularly in hard to understand areas)
    * There are no new warnings that can be corrected
    * Commits policy is respected (constitancy commits, clear commits comments)
<hr/><br>

### _3- QA section_

- [ ] [Review] tests for new features have been *reviewed*
- [ ] [Changelog] is up-to-date with expected tags  
    🆕 Feature: [Feature] Description...  
    🆕 Added: [Feature] Description...  
    🆕 Changed: [Feature] Description...  
    🛠️ Fix: [Feature] Description...

2022-08-08 16:22 UTC, K0rdan requested changes

2022-08-08 16:22 UTC, K0rdan commented on CONTRIBUTING.md
> +<a href="https://luos.io"><img src="https://uploads-ssl.webflow.com/601a78a2b5d030260a40b7ad/603e0cc45afbb50963aa85f2_Gif%20noir%20rect.gif" alt="Luos logo" title="Luos" align="right" height="100" />
Don't use old webflow image

2022-08-08 16:24 UTC, Simonbdy commented on CONTRIBUTING.md
> +Contribution allows contributors to learn faster and gain skills. In fact, some contributors in open source projects became quite famous and were able to build their carreer around their contribution
`why`, I think!
Thanks

2022-08-09 08:04 UTC, Simonbdy commented
@K0rdan, all your modif requests have been done.

2022-08-09 14:57 UTC, K0rdan commented on CONTRIBUTING.md
> +<a href="https://luos.io"><img src="https://uploads-ssl.webflow.com/601a78a2b5d030260a40b7ad/603e0cc45afbb50963aa85f2_Gif%20noir%20rect.gif" alt="Luos logo" title="Luos" align="right" height="100" />
```<img src="https://www.luos.io/img/logo_luos_animated_white.gif" alt="Luos logo" title="Luos" align="right" height="100" />```

2022-08-09 15:16 UTC, K0rdan approved these changes

2022-08-09 16:03 UTC, merged